package t2

//之所以会报错 是因为 同一个 目录下 只允许 存在一个 包名 。 因为 我们 test 目录下 有两个 包名 t1 和 t2 所以 会报错
func main() {

}
